package gunging.ootilities.gunging_ootilities_plugin.customstructures;

public enum CSTrigger {
    INTERACT,
    SNEAK_INTERACT,
    PUNCH,
    SNEAK_PUNCH,
    COMPLETE,
    SNEAK_COMPLETE,
    BREAK,
    SNEAK_BREAK,
    PRESSUREPLATE_MONSTERS,
    PRESSUREPLATE_ANIMALS,
    PRESSUREPLATE_ITEMS,
    PRESSUREPLATE_PLAYERS_CONTINUOS,
    SNEAK_PRESSUREPLATE_PLAYERS_CONTINUOUS,
    PRESSUREPLATE_PLAYERS,
    SNEAK_PRESSUREPLATE_PLAYERS
    //PRESSUREPLATE_MINECARTRAIL_PLAYER,
    //PRESSUREPLATE_MINECARTRAIL_EMPTY,
    //PRESSUREPLATE_MINECARTRAIL_MONSTER,
    //PRESSUREPLATE_MINECARTRAIL_ANIMAL,
    //PRESSUREPLATE_MINECARTRAIL_OTHER,
}
